enum game_code
{
	RESULT_SUCCESS = 0,

	RESULT_FAILED_INVAILD_ACCOUNT = 301,	//输入的帐号无效
	RESULT_FAILED_INVAILD_PASSWORD = 302,	//输入的密码无效
	RESULT_FAILED_ACCOUNT_LIMIT = 302,		//帐号超过限制长度
	RESULT_FAILED_PASSWORD_LIMIT = 303,		//密码超过限制长度
	RESULT_FAILED_ACCOUNT_ALREADY = 304,	//帐号已存在
	RESULT_FAILED_LOGIN_ACCOUNT_INVAILD = 305,	//登录帐号无效
	RESULT_FAILED_LOGIN_PASSWORD_INVAILD = 306,	//登录密码无效
	RESULT_FAILED_LOGIN_ACCOUNT_LIMIT = 307,		//登录帐号超过限制长度
	RESULT_FAILED_LOGIN_PASSWORD_LIMIT = 308,		//登录密码超过限制长度
	RESULT_FAILED_LOGIN_ACCOUNT_NOT_EXIST = 309,	//登录的帐号不存在
	RESULT_FAILED_LOGIN_PASSWORD_ERROR = 310,		//登录的密码错误
	RESULT_FAILED_LOGIN_TIME_LIMIT = 311,			//登录时间限制为2秒内只能登录1次
	RESULT_FAILED_CLIENT_CLOSED_NOT_EXIST = 312,	//客户端关闭的信息不存在
	RESULT_FAILED_LOGIN_ONLINE_INFO_NOT_EXIST = 313,		//客户端关闭的登录在线信息不存在
	RESULT_FAILED_ROLE_NICKNAME_INVAILD = 314,		//角色昵称无效
	RESULT_FAILED_ROLE_NICKNAME_LIMIT = 315,		//角色昵称过长
	RESULT_FAILED_ROLE_COUNT_FULL = 316,		//角色个数已满
	RESULT_FAILED_ROLE_SEX_INVAILD = 317,		//角色性别无效
	RESULT_FAILED_USERID_INVAILD = 318,			//用户ID无效
	RESULT_FAILED_FIND_USERS_NOT_EXIST = 319,		//需要查找的用户们不存在
	RESULT_FAILED_ROLEID_INVAILD = 320,			//角色ID无效
	RESULT_FAILED_USER_NOT_REGISTER = 321,		//用户没有注册
};